/*
-- Query: SELECT * FROM morphalounouv.lex2_inflectionaveccollate
-- Date: 2012-07-30 09:32
*/
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (1,'aalénien','singular',NULL,NULL,NULL,NULL,'a l e n j e~','a l E/ n j e~',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (1,'aaléniens','plural',NULL,NULL,NULL,NULL,'a l e n j e~','a l E/ n j e~',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (2,'aalénien','singular',NULL,'masculine',NULL,NULL,'a l e n j e~','a l E/ n j e~',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (2,'aaléniens','plural',NULL,'masculine',NULL,NULL,'a l e n j e~','a l E/ n j e~',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (2,'aalénienne','singular',NULL,'feminine',NULL,NULL,'a l e n j E n @','a l E/ n j E n @',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (2,'aaléniennes','plural',NULL,'feminine',NULL,NULL,'a l e n j E n @','a l E/ n j E n @',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (3,'aba','singular',NULL,NULL,NULL,NULL,'a b a','a b a',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (3,'abas','plural',NULL,NULL,NULL,NULL,'a b a','a b a',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (4,'abaca','singular',NULL,NULL,NULL,NULL,'a b a k a','a b a k a',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (4,'abacas','plural',NULL,NULL,NULL,NULL,'a b a k a','a b a k a',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (5,'abaddir','singular',NULL,NULL,NULL,NULL,'a b a d i R','a b a d i R',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (5,'abaddirs','plural',NULL,NULL,NULL,NULL,'a b a d i R','a b a d i R',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (6,'abada','singular','indicative',NULL,'simplePast','thirdPerson','a b a d a','a b a d a',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (6,'abadai','singular','indicative',NULL,'simplePast','firstPerson','a b a d e','a b a d e',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (6,'abadaient','plural','indicative',NULL,'imperfect','thirdPerson','a b a d E','a b a d E',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (6,'abadais','singular','indicative',NULL,'imperfect','firstPerson','a b a d E','a b a d E',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (6,'abadais','singular','indicative',NULL,'imperfect','secondPerson','a b a d E','a b a d E',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (6,'abadait','singular','indicative',NULL,'imperfect','thirdPerson','a b a d E','a b a d E',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (6,'abadant',NULL,'participle',NULL,'present',NULL,'a b a d a~','a b a d a~',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (6,'abadas','singular','indicative',NULL,'simplePast','secondPerson','a b a d a','a b a d a',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (6,'abadasse','singular','subjunctive',NULL,'imperfect','firstPerson','a b a d a s @','a b a d a s @',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (6,'abadassent','plural','subjunctive',NULL,'imperfect','thirdPerson','a b a d a s @','a b a d a s @',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (6,'abadasses','singular','subjunctive',NULL,'imperfect','secondPerson','a b a d a s @','a b a d a s @',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (6,'abadassiez','plural','subjunctive',NULL,'imperfect','secondPerson','a b a d a s j e','a b a d a s j e',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (6,'abadassions','plural','subjunctive',NULL,'imperfect','firstPerson','a b a d a s j o~','a b a d a s j o~',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (6,'abade','singular','indicative',NULL,'present','firstPerson','a b a d @','a b a d @',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (6,'abade','singular','indicative',NULL,'present','thirdPerson','a b a d @','a b a d @',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (6,'abade','singular','subjunctive',NULL,'present','firstPerson','a b a d @','a b a d @',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (6,'abade','singular','subjunctive',NULL,'present','thirdPerson','a b a d @','a b a d @',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (6,'abade','singular','imperative',NULL,'present','secondPerson','a b a d @','a b a d @',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (6,'abadent','plural','indicative',NULL,'present','thirdPerson','a b a d @','a b a d @',NULL,NULL,NULL,NULL);
INSERT INTO `test` (`entryID`,`content`,`number`,`mood`,`gender`,`tense`,`person`,`phonetic1`,`phonetic2`,`originatingEntry`,`dateCreation`,`dateModification`,`Remarques`) VALUES (6,'abadent','plural','subjunctive',NULL,'present','thirdPerson','a b a d @','a b a d @',NULL,NULL,NULL,NULL);
