SELECT * 
FROM LEX2_inflection
WHERE phonetic1 LIKE "%j e%" AND phonetic1 NOT LIKE "%j e~%"
AND content NOT LIKE "%ié%"
AND content NOT LIKE "%yé%"
AND content NOT LIKE "%ille%"
AND content NOT LIKE "%ie%"
AND content NOT LIKE "%iœ%"
AND content NOT LIKE "%iai%"
AND content NOT LIKE "%ïé%"
AND content NOT LIKE "%ye%"
AND content NOT LIKE "%ïer"

AND content NOT LIKE "%ïers"
AND content NOT LIKE "%ier"
AND content NOT LIKE "%yiais"
AND content NOT LIKE "%iais"
AND content NOT LIKE "%illais"
AND content NOT LIKE "%jé"
AND content NOT LIKE "%jés"
AND content NOT LIKE "%iehs"
AND content NOT LIKE "%ieh"
AND content NOT LIKE "%yais"
AND content NOT LIKE "%iez"
AND content NOT LIKE "%illers"
AND content NOT LIKE "%iller"
AND content NOT LIKE "%illé"
AND content NOT LIKE "%illée"
AND content NOT LIKE "%illées"
AND content NOT LIKE "%illée"
AND content NOT LIKE "%iers"
AND content NOT LIKE "%ier"
AND content NOT LIKE "%yai"
AND content NOT LIKE "%yer"
AND content NOT LIKE "%yez"
AND content NOT LIKE "%yés"
AND content NOT LIKE "%illés"
AND content NOT LIKE "%yé"
AND content NOT LIKE "%yées"
AND content NOT LIKE "%iai"
AND content NOT LIKE "%iés"
AND content NOT LIKE "%ié"
AND content NOT LIKE "%iées"
AND content NOT LIKE "%iée"
AND content NOT LIKE "%illai"
AND content NOT LIKE "%illez"
AND content NOT LIKE "%ieds"
AND content NOT LIKE "%yée"
AND content NOT LIKE "%ied"
AND content NOT LIKE "%yers"
AND content NOT LIKE "%yée"

