SELECT * 
FROM LEX2_inflection
WHERE phonetic1 LIKE "%j a~%"
AND content NOT LIKE "%yant"
AND content NOT LIKE "%yants"
AND content NOT LIKE "%iant"
AND content NOT LIKE "%iants"
AND content NOT LIKE "%ian"
AND content NOT LIKE "%ians"
AND content NOT LIKE "%yan"
AND content NOT LIKE "%yans"
AND content NOT LIKE "%illant"
AND content NOT LIKE "%illants"
AND content NOT LIKE "%yant"
AND content NOT LIKE "%iand"
AND content NOT LIKE "%iands"
AND content NOT LIKE "%illan"
AND content NOT LIKE "%illans"
AND content NOT LIKE "%ient"
AND content NOT LIKE "%ients"

AND content NOT LIKE "%yan%"
AND content NOT LIKE "%ian%"
AND content NOT LIKE "%illan%"
AND content NOT LIKE "%ien%"
AND content NOT LIKE "%iam%"
AND content NOT LIKE "%ïen%"
AND content NOT LIKE "%ïam%"