SELECT * 
FROM LEX2_inflection
WHERE phonetic1 LIKE "%j E%"
AND content NOT LIKE "%ie%"
AND content NOT LIKE "%illè%"
AND content NOT LIKE "%yè%"
AND content NOT LIKE "%iè%"
AND content NOT LIKE "%iai%"
AND content NOT LIKE "%ille%"
AND content NOT LIKE "%illai%"
AND content NOT LIKE "%ye%"
AND content NOT LIKE "%ïe%"
AND content NOT LIKE "%ïè%"
AND content NOT LIKE "%yai%"
AND content NOT LIKE "%yaient"
AND content NOT LIKE "%yais"
AND content NOT LIKE "%yait"
AND content NOT LIKE "%iaient"
AND content NOT LIKE "%iais"
AND content NOT LIKE "%iait"
AND content NOT LIKE "%illaient"
AND content NOT LIKE "%illais"
AND content NOT LIKE "%illait"
AND content NOT LIKE "%illets"
AND content NOT LIKE "%illet"
AND content NOT LIKE "%ïet"
AND content NOT LIKE "%ïets"
AND content NOT LIKE "%iai"
AND content NOT LIKE "%iehs"
AND content NOT LIKE "%ieh"
AND content NOT LIKE "%iets"
AND content NOT LIKE "%iet"
AND content NOT LIKE "%yets"
AND content NOT LIKE "%yet"


