SELECT * 
FROM LEX2_inflection
WHERE phonetic1 LIKE "%j a%" AND phonetic1 NOT LIKE "%j a~%"
AND content NOT LIKE "%iat"
AND content NOT LIKE "%iats"
AND content NOT LIKE "%ya"
AND content NOT LIKE "%yas"
AND content NOT LIKE "%yât"
AND content NOT LIKE "%ias"
AND content NOT LIKE "%iât"
AND content NOT LIKE "%ia"
AND content NOT LIKE "%illa"
AND content NOT LIKE "%illas"
AND content NOT LIKE "%illât"
AND content NOT LIKE "%illat"
AND content NOT LIKE "%illats"
AND content NOT LIKE "%illat"
AND content NOT LIKE "%illats"
AND content NOT LIKE "%yat"
AND content NOT LIKE "%yats"
AND content NOT LIKE "%ïa"
AND content NOT LIKE "%ïas"

AND content NOT LIKE "%tia%"
AND content NOT LIKE "%illa%"
AND content NOT LIKE "%ya%"
AND content NOT LIKE "%yâ%"
AND content NOT LIKE "%ia%"
AND content NOT LIKE "%iâ%"
AND content NOT LIKE "%illâ%"
AND content NOT LIKE "%ïa%"
AND content NOT LIKE "%ie%"
AND content NOT LIKE "%lla%"


