SELECT * 
FROM LEX2_inflection
WHERE phonetic1 LIKE "%w E%"
AND content NOT LIKE "%uais%"
AND content NOT LIKE "%uait%"
AND content NOT LIKE "%uaient%"
AND content NOT LIKE "%we%"
AND content NOT LIKE "%ouai%"
AND content NOT LIKE "%ouets"
AND content NOT LIKE "%ouet"
AND content NOT LIKE "%oè%"
AND content NOT LIKE "%ways%"
AND content NOT LIKE "%way%"
AND content NOT LIKE "%oe%"
AND content NOT LIKE "%ua%"
AND content NOT LIKE "%wa%"
AND content NOT LIKE "%uè%"
AND content NOT LIKE "%oue%"
AND content NOT LIKE "%ue%"