SELECT * 
FROM LEX2_inflection
WHERE phonetic1 LIKE "%j o%" AND phonetic1 NOT LIKE "%j o~%"
AND content NOT LIKE "%iaux"
AND content NOT LIKE "%ios"
AND content NOT LIKE "%io"
AND content NOT LIKE "%illots"
AND content NOT LIKE "%illot"
AND content NOT LIKE "%iau"
AND content NOT LIKE "%illhauts"
AND content NOT LIKE "%illaut"
AND content NOT LIKE "%yau"
AND content NOT LIKE "%yaux"
AND content NOT LIKE "%yos"
AND content NOT LIKE "%yo"
AND content NOT LIKE "%iau"
AND content NOT LIKE "%illo"
AND content NOT LIKE "%illos"
AND content NOT LIKE "%ïauts"
AND content NOT LIKE "%ïaut"
AND content NOT LIKE "%hyaux"
AND content NOT LIKE "%illots"
AND content NOT LIKE "%illot"
AND content NOT LIKE "%iauds"
AND content NOT LIKE "%iaud"
AND content NOT LIKE "%iaut"
AND content NOT LIKE "%iauts"
AND content NOT LIKE "%yauds"
AND content NOT LIKE "%yaud"
AND content NOT LIKE "%ilhaut"
AND content NOT LIKE "%ilhauts"
AND content NOT LIKE "%illaud"
AND content NOT LIKE "%ilauds"
AND content NOT LIKE "%iots"
AND content NOT LIKE "%iot"
AND content NOT LIKE "%illods"
AND content NOT LIKE "%illauds"
AND content NOT LIKE "%yots"
AND content NOT LIKE "%yot"
AND content NOT LIKE "%iaus"

AND content NOT LIKE "%io%"
AND content NOT LIKE "%iau%"
AND content NOT LIKE "%illau%"
AND content NOT LIKE "%yau%"
AND content NOT LIKE "%iô%"
AND content NOT LIKE "%yach%"
AND content NOT LIKE "%yaw%"
AND content NOT LIKE "%yo%"

